### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: lora
lora_rank: 64
lora_target: all
lora_dropout: 0.1
lora_alpha: 128

### dataset
dataset: peter_multimodal_train_row, peter_multimodal_train_row_55k_synthetic, peter_multimodal_train_row_pack2_synthetic, peter_multimodal_train_row_pack4_synthetic
eval_dataset: peter_multimodal_val_row
template: qwen2_vl
cutoff_len: 2048
max_samples: 150000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: output_dir/qwen_lora
logging_steps: 50
save_strategy: steps
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 5.0e-4
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_ratio: 0.02
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: Null
use_liger_kernel: true
deepspeed: ../LLaMA-Factory/examples/deepspeed/ds_z3_config.json
report_to: wandb
run_name: "example_run_name"

### eval
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 200
load_best_model_at_end: true
greater_is_better: false
metric_for_best_model: eval_loss